// Invitation management — used by the admin portal and the /accept
// flow. The token column has a server-side default (gen_random_bytes
// via pgcrypto), so the client never generates them.

import { supabase } from '$lib/supabase';
import type { Database } from '$lib/database.types';
import type { MembershipRole } from './regionService';

export type Invitation = Database['public']['Tables']['invitations']['Row'];

const DEFAULT_EXPIRY_DAYS = 14;

/** All invitations for a region the caller can read (admin-only via RLS). */
export async function listForRegion(regionId: string): Promise<Invitation[]> {
  const { data, error } = await supabase
    .from('invitations')
    .select('*')
    .eq('region_id', regionId)
    .order('created_at', { ascending: false });
  if (error) {
    console.error('[invitationService] listForRegion error:', error);
    throw error;
  }
  return data ?? [];
}

export interface CreateInput {
  regionId: string;
  email: string;
  role: MembershipRole;
  expiresInDays?: number;
}

/** Send an invitation. Re-uses an existing pending row for the same
 *  (region, email) instead of creating a duplicate — the partial
 *  unique index guarantees there can only be one. */
export async function createOrRefresh(input: CreateInput): Promise<Invitation> {
  const { data: userData } = await supabase.auth.getUser();
  const inviter = userData.user?.id;
  if (!inviter) throw new Error('Not signed in.');

  const email = input.email.trim().toLowerCase();
  const expires = new Date(
    Date.now() + (input.expiresInDays ?? DEFAULT_EXPIRY_DAYS) * 86_400_000
  ).toISOString();

  // Look for an existing pending invite first.
  const { data: existing, error: existingErr } = await supabase
    .from('invitations')
    .select('*')
    .eq('region_id', input.regionId)
    .eq('email', email)
    .is('accepted_at', null)
    .maybeSingle();
  if (existingErr) throw existingErr;

  if (existing) {
    // Refresh expiry + role + inviter, keep the same token so a
    // previously shared link still works.
    const { data, error } = await supabase
      .from('invitations')
      .update({ role: input.role, expires_at: expires, invited_by: inviter })
      .eq('id', existing.id)
      .select()
      .single();
    if (error) throw error;
    return data;
  }

  // Token is generated by the column default.
  const { data, error } = await supabase
    .from('invitations')
    .insert({
      region_id: input.regionId,
      email,
      role: input.role,
      invited_by: inviter,
      expires_at: expires
    })
    .select()
    .single();
  if (error) {
    console.error('[invitationService] create error:', error);
    throw error;
  }
  return data;
}

export async function revoke(invitationId: string): Promise<void> {
  const { error } = await supabase.from('invitations').delete().eq('id', invitationId);
  if (error) {
    console.error('[invitationService] revoke error:', error);
    throw error;
  }
}

/** Build the canonical accept-link for an invitation. Caller supplies
 *  the public origin (e.g. https://judithhubbard.github.io/forager). */
export function acceptUrl(origin: string, token: string): string {
  const clean = origin.replace(/\/$/, '');
  return `${clean}/accept?token=${encodeURIComponent(token)}`;
}
