-- Drop the now-obsolete usda_zones_dissolved table + the
-- usda_zones_geojson() RPC that read from it. Both were the first
-- attempt at server-side simplification (migration 28); the resulting
-- payload required ~40s ST_AsGeoJSON serialization on every call,
-- and PostGIS 3.3 lacks ST_CoverageSimplify so the per-feature
-- ST_SimplifyPreserveTopology produced misaligned edges between
-- adjacent zone polygons.
--
-- We now ship static/usda-zones.geojson generated by mapshaper
-- (npm run regen:usda-zones-static), which builds a topology before
-- simplifying so shared boundaries stay aligned.
--
-- usda_hardiness_zones (the raw 30k-row source) and zone_for_point()
-- stay — they're still used for per-pin climate_zone_id assignment.

drop function if exists public.usda_zones_geojson();
drop table if exists public.usda_zones_dissolved cascade;
