-- Migration 30: confirmed-window protection + audit log.
--
-- The unify pipeline rewrites every species' windows on every run.
-- That's fine while a species' calibration is iterating, but once
-- JK has personally reviewed and signed off on a species (review_
-- status='confirmed'), we don't want the next unify rerun to silently
-- overwrite the carefully-checked values.
--
-- Design:
--   1. Append-only `confirmed_window_exports` table snapshots the
--      full window set at the moment of confirmation. Timestamped,
--      stores the actor's user_id, and includes optional notes about
--      what changed since the last export. Pure audit log — never
--      mutated after insert. The newest export per species is the
--      "current truth."
--
--   2. `species_fruiting_windows.is_confirmed` boolean flag marks
--      individual rows as part of an active confirmed export. The
--      unify pipeline SKIPS writes to rows where is_confirmed=true.
--      Cleared when a re-export happens (immediately re-set after
--      the new snapshot is written, so the gap is microsecond-scale).
--
--   3. Companion git-tracked JSON dump at
--      data/confirmed-windows/<scientific_name>-<timestamp>.json
--      lives outside the DB. Acts as a reviewable receipt — diffs
--      visible in PRs, restorable if the DB is ever rolled back.
--      Generated by scripts/confirm-species.cjs alongside the DB
--      writes; not enforced by the schema.
--
-- The drift-detection script (scripts/check-confirmed-drift.cjs,
-- ships in a follow-up commit per JK's "two passes" plan) will
-- compare live unify-pipeline output against the latest export
-- per confirmed species and surface deltas for JK to review.

create table if not exists public.confirmed_window_exports (
  id            uuid primary key default gen_random_uuid(),
  species_id    uuid not null references public.species(id) on delete cascade,
  exported_at   timestamptz not null default now(),
  exported_by   uuid references auth.users(id),
  -- All windows for this species captured at the moment of
  -- confirmation. JSONB array of { climate_zone_code, stage,
  -- start_doy, end_doy, peak_doy, confidence, notes, evidence,
  -- complex_name }. Stored verbatim — never normalized into
  -- relational rows; the active rows in species_fruiting_windows
  -- with is_confirmed=true ARE the relational form.
  windows_snapshot jsonb not null,
  -- Optional human note describing what changed in this export
  -- compared to the previous one. Helps future-JK remember why
  -- a given re-export happened.
  notes         text
);

create index if not exists confirmed_exports_species_idx
  on public.confirmed_window_exports (species_id, exported_at desc);

comment on table public.confirmed_window_exports is
  'Append-only audit log of confirmed-window snapshots. Each row is a full snapshot of a species window set at the moment of confirmation. Newest row per species is the active confirmed state.';

-- Per-row flag: is this individual window part of the active
-- confirmed export? Set + cleared by scripts/confirm-species.cjs.
-- Read by scripts/species-complex-unify.cjs to know which rows
-- to skip during automated regeneration.
alter table public.species_fruiting_windows
  add column if not exists is_confirmed boolean not null default false;

comment on column public.species_fruiting_windows.is_confirmed is
  'TRUE when this row was part of a confirm-species export and should be left alone by automated pipelines. See confirmed_window_exports for the audit history.';

-- Index used by the unify pipeline's skip check ("which species
-- have any confirmed rows, skip those entirely").
create index if not exists sfw_is_confirmed_idx
  on public.species_fruiting_windows (species_id)
  where is_confirmed = true;
